config/routes.rb
Rails.application.routes.draw do

  resources :calendars
  resources :professors
  resources :lessons
  resources :periods
  resources :commissions
  resources :subjects
  resources :rooms
  resources :availabilities
  resources :shifts
  resources :days
  resources :years
  resources :careers
  resources :professors
  resources :resources
  resources :sessions

  get 'professors/:id/custom', :to => 'professors#custom'
  get 'careers/:id/custom', :to => 'careers#custom'
  get 'subjects/:id/custom', :to => 'subjects#custom'

  root 'calendars#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">


  <%= favicon_link_tag 'favicon.ico' %>

  <title>Shifter</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!--[if lt IE 9]>-->
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <!--<![endif]-->

</head>

<div id="processing" class="panel panel-primary" hidden>
  <div class="panel-heading"><i class="fa fa-spinner fa-fw"></i> Procesando</div>
  <div class="panel-body">
    <div class="row">
      <div class="col-lg-12">
        Esto puede demorar unos segundos...
      </div>
    </div>
  </div>
</div>
<div id="shade" hidden></div>

<body>

<% if current_user %>
<div id="wrapper">
  <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
      <a class="navbar-brand" href="/" style="font-family: 'Palatino Linotype', 'Book Antiqua', Palatino, serif; font-size: 25px; padding-left: 10px"><i class="fa fa-graduation-cap fa-fw"></i> Shifter</a>
    </div>
    <ul class="nav navbar-top-links navbar-right">
      <li>
        <p class="text-muted"><i class="fa fa-user fa-fw"></i> Bienvenido, <b><%= current_user.email %></b></p>
      </li>
      <li>
        <%= link_to 'Cerrar sesión', session_path('current'), method: 'delete' %></a>
      </li>
    </ul>

    <div class="navbar-default sidebar" role="navigation">
      <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
          <li>
            <a href="/calendars" class="menu"><i class="fa fa-calendar fa-fw"></i> Mis Horarios</a>
          </li>
          <li>
            <a href="/lessons/new" class="menu"><i class="fa fa-plus fa-fw"></i> Nuevo Horario</a>
          </li>
          <li>
            <a href="/careers" class="menu"><i class="fa fa-graduation-cap fa-fw"></i> Carreras</a>
          </li>
          <li>
            <a href="/subjects" class="menu"><i class="fa fa-pencil fa-fw"></i> Materias</a>
          </li>
          <li>
            <a href="/professors" class="menu"><i class="fa fa-user fa-fw"></i> Profesores</a>
          </li>
          <li>
            <a href="/periods/new" class="menu"><i class="fa fa-user-plus fa-fw"></i> Asignaciones</a>
          </li>
          <li>
            <a href="/rooms" class="menu"><i class="fa fa-building fa-fw"></i> Aulas</a>
          </li>
          <li>
            <a href="/resources" class="menu"><i class="fa fa-tv fa-fw"></i> Recursos</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div id="page-wrapper">
    <% end %>
    <%= yield %>
    <% if current_user %>
  </div>
</div>
<% end %>
<script type="text/javascript" charset="utf-8">
  $( document ).ready(function() {
    fix();
  });
</script>
</body>

</html>